#v20210129 by alex@rk86.com
FROM docker.io/bitnami/redmine:4-debian-10
#RUN apt-get update
#RUN apt-get upgrade
RUN install_packages iputils-ping net-tools telnet nano htop subversion mc build-essential libmariadb-dev libpq-dev pkg-config libmagickwand-dev
