# v20220518 by alex@rk86.com
# https://github.com/Bitnami/bitnami-docker-redmine
FROM docker.io/bitnami/redmine:5.0.1-debian-10-r1
#RUN apt-get update
#RUN apt-get upgrade
RUN install_packages iputils-ping net-tools telnet nano htop subversion mc build-essential libmariadb-dev libpq-dev pkg-config libmagickwand-dev
